---
- name: add apt key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB

- name: add apt repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"

# The package order is important, otherwise 'kubeadm' would install the latest
# version of the others as its dependencies ignoring the version pinning.
- name: install packages
  apt:
    name:
      - "kubelet={{ kubernetes_version }}-00"
      - "kubectl={{ kubernetes_version }}-00"
      - "kubeadm={{ kubernetes_version }}-00"

- name: hold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubectl
    - kubeadm

- name: copy bootstrap script
  copy:
    src: init-cluster.sh
    dest: /usr/local/bin/init-cluster.sh
    mode: 0755
