---
- name: install package
  apt:
    name: apt-transport-https

- name: add repository key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: add repository url
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      {{ ansible_distribution_release }} stable"

- name: install package
  apt:
    name: docker-ce
